//
//  GrocerySections.swift
//  Porika_GroceryApp
//
//  Created by Student on 4/12/22.
//

import Foundation


struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let grocery1 = Grocery(section:"Dairy",items_Array:[GroceryItem(itemName:"Chocolate Milk",itemImage:"chocolate_milk",itemInfo:"Chocolate milk is generally made by mixing cow's milk with cocoa and sweeteners like sugar or high-fructose corn syrup. It's richer in carbs and calories than unsweetened milk but otherwise contains similar levels of nutrients"), GroceryItem(itemName: "Goat Milk", itemImage: "Goat_milk", itemInfo: "A milk product that is provided from the mammary glands of goats. Goat milk is popular in some parts of the world and believed to be more easily digested than other forms of milk from cows."), GroceryItem(itemName: "Lowfat Milk", itemImage: "lowfat_milk", itemInfo: "Generally low-fat milk has been fortified with vitamin A and D and may also have been fortified with non-fat milk powder to enhance the flavor, making the milk richer tasting. An 8 ounce serving of low-fat milk provides approximately 312 mg of calcium, 2.2 grams of fat and 104 calories"), GroceryItem(itemName: "Skimmed Milk Powdered", itemImage: "SKIMMED-MILK-POWDED", itemInfo: "Milk powder is milk that has been turned into a dry substance by evaporating its water content. This increases its shelf life and results in a product that is extremely suitable for use in the food and beverage industry"), GroceryItem(itemName: "Whole Milk", itemImage: "whole_milk", itemInfo: "Milk containing at least 3.25 percent milk fat, which is present when it is provided from the cow. None of the milk fat is removed from whole milk and it is not fortified with Vitamin A as are the different varieties of reduced fat milk. Whole milk will have a creamier and richer taste than the lower fat milks")] )

let grocery2 = Grocery( section: "Snacks", items_Array: [GroceryItem(itemName: "Lays", itemImage: "lays", itemInfo: "So every Lays potato chip is perfectly crispy and delicious. Happiness in every bite. Made with all natural ingredients. Ingredients Potatoes, Vegetable Oil (Sunflower, Corn and/or Canola Oil), and Salt."), GroceryItem(itemName: "Doritos", itemImage: "Doritos", itemInfo: "Doritos is an American brand of flavored tortilla chips produced since 1964 by Frito-Lay, a wholly owned subsidiary of PepsiCo. The original Doritos were not flavored. The first flavor was Toasted Corn, released in 1966, followed by Taco in 1967 and Nacho Cheese in 1972"), GroceryItem(itemName: "Oreo Biscuits", itemImage: "Oreo_biscuit", itemInfo: "Oreo cookies are technically vegan, according to Delish. The ingredients are fairly simple and include sugar, flour, oil, cocoa, high fructose corn syrup, leavening, cornstarch, salt, soy lecithin, vanillin, and chocolate"), GroceryItem(itemName: "Cheetos", itemImage: "cheetos", itemInfo: "Enriched Corn Meal (Corn Meal, Ferrous Sulfate, Niacin, Thiamin Mononitrate, Riboflavin, Folic Acid), Vegetable Oil (Corn, Canola, and/or Sunflower Oil), Cheese Seasoning (Whey, Cheddar Cheese [Milk, Cheese Cultures, Salt, Enzymes], Canola Oil, Maltodextrin [Made from Corn], Natural and Artificial Flavors"), GroceryItem(itemName: "Salt Biscuits", itemImage: "salt_biscuits", itemInfo: "Salted biscuit is a large diameter biscuit that has a crumbly texture and a salty flavour, which is quite tempting to people of all age groups. It goes well with tea and coffee, and can be used as a canapé too")] )

let grocery3 = Grocery( section: "Meat", items_Array: [GroceryItem(itemName: "Beef", itemImage: "beef", itemInfo: "Beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed"), GroceryItem(itemName: "chicken", itemImage: "chicken", itemInfo: "A chicken is a bird. One of the features that differentiate it from most other birds is that it has a comb and two wattles. The comb is the red appendage on the top of the head, and the wattles are the two appendages under the chin. These are secondary sexual characteristics and are more prominent in the male"), GroceryItem(itemName: "Lamb", itemImage: "lamb", itemInfo: "Lamb is a baby sheep, the meat of sheep, a gentle or sweet person, or someone who is easily fooled because of inexperience. A newborn sheep is an example of a lamb. The meat traditionally used to make shepherd's pie"), GroceryItem(itemName: "Mutton", itemImage: "mutton", itemInfo: "Mutton refers to the flesh of the mature ram or ewe at least one year old; the meat of sheep between 12 and 20 months old may be called yearling mutton. The meat of sheep 6 to 10 weeks old is usually sold as baby lamb, and spring lamb is from sheep of age five to six months."), GroceryItem(itemName: "Pork", itemImage: "pork", itemInfo: "Pork, flesh of hogs, usually slaughtered between the ages of six months and one year. The most desirable pork is grayish pink in colour, firm and fine-grained, well-marbled, and covered with an outer layer of firm white fat")] )

let grocery4 = Grocery( section: "Veggies", items_Array: [GroceryItem(itemName: "Broccoli", itemImage: "Broccoli", itemInfo: "The vegetable consists of a dark green head (made up of small flowers or florets), a light green stalk, and large green leaves. Its tree-like structure resembles cauliflower. A rich source of vitamins C and K, broccoli has an earthy flavor that's ever-so-slightly bitter. It's commonly eaten raw or cooked"), GroceryItem(itemName: "Tomato", itemImage: "tomato", itemInfo: "They are usually red, scarlet, or yellow, though green and purple varieties do exist, and they vary in shape from almost spherical to oval and elongate to pear-shaped. Each fruit contains at least two cells of small seeds surrounded by jellylike pulp. hothouse tomatoes"), GroceryItem(itemName: "GreenPeas", itemImage: "greenpeas", itemInfo: "Green peas, or “garden peas,” are the small, spherical seeds that come from pods produced by the Pisum sativum plant. They have been part of the human diet for hundreds of years and are consumed all over the world. Strictly speaking, green peas are not vegetables"), GroceryItem(itemName: "Carrot", itemImage: "carrot", itemInfo: "carrot, (Daucus carota), herbaceous, generally biennial plant of the Apiaceae family that produces an edible taproot. Among common varieties root shapes range from globular to long, with lower ends blunt to pointed. Besides the orange-coloured roots, white-, yellow-, and purple-fleshed varieties are known."), GroceryItem(itemName: "Capsicum", itemImage: "capsicum", itemInfo: "Capsicum, also known as red pepper or chili pepper, is an herb. Its fruit is commonly applied to the skin for arthritis pain and other conditions. The fruit of the capsicum plant contains a chemical called capsaicin. Capsaicin is what seems to help reduce pain and swelling")] )

let grocery5 = Grocery( section: "Bakery", items_Array: [GroceryItem(itemName: "Bread", itemImage: "bread", itemInfo: "Bread, baked food product made of flour or meal that is moistened, kneaded, and sometimes fermented. A major food since prehistoric times, it has been made in various forms using a variety of ingredients and methods throughout the world"), GroceryItem(itemName: "Cakes", itemImage: "cakes", itemInfo: "Cake, in general, any of a variety of breads, shortened or unshortened, usually shaped by the tin in which it is baked, or, more specifically, a sweetened bread, often rich or delicate"), GroceryItem(itemName: "Sandwich", itemImage: "sandwich", itemInfo: "Sandwich, in its basic form, slices of meat, cheese, or other food placed between two slices of bread. Although this mode of consumption must be as old as meat and bread, the name was adopted only in the 18th century for John Montagu,"), GroceryItem(itemName: "Donuts", itemImage: "donuts", itemInfo: "A donut, also called doughnut, is a kind of fried dough confectionery. Donuts are typically ring shaped with a hole in the middle. Bakers also make oval shaped donuts, which are often filled with custards or fruit preserves"), GroceryItem(itemName: "Pizza", itemImage: "c5", itemInfo: "Pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients, baked quickly—usually, in a commercial setting, using a wood-fired oven heated to a very high temperature—and served hot")] )


let grocerys = [grocery1, grocery2, grocery3, grocery4, grocery5]

