//
//  MovieData.swift
//  Porika_Movies
//
//  Created by student on 4/28/22.
//

import Foundation
import UIKit

struct Movie {
    var title:String
    var image:UIImage
    var releasedYear:String
    var movieRating:String
    var boxOffice:String
    var moviePlot:String
    var cast:[String] = []
}

struct Genre {
    var type:String = ""
    var movies:[Movie] = []
}

let type1: Genre = Genre(type: "Thriller", movies: [Movie(title: "NightHouse", image: UIImage(named: "NightHouse")!, releasedYear: "2020", movieRating: "6.5", boxOffice: "$15.5 million", moviePlot: "Beth has just lost her husband Owen to suicide. Devastated, she spends her nights drinking and going through Owen's belongings. She tries to appear stable and in control, but her friend Claire and neighbour Mel are concerned for her. Owen's ominous suicide note.", cast: ["Rebecca Hall", "Sarah Goldberg"]), Movie(title: "Malignant", image: UIImage(named: "Malignant")!, releasedYear: "2021", movieRating: "6.2", boxOffice: "$34 Million", moviePlot: "Paralyzed by fear from shocking visions, a woman's torment worsens as she discovers her waking dreams are terrifying realities.", cast: ["James Wan", "Ingrid Bisu"]), Movie(title: "TheRental", image: UIImage(named: "TheRental")!, releasedYear: "2020", movieRating: "5.7", boxOffice: "3.4 million", moviePlot: "Two couples on an oceanside getaway grow suspicious that the host of their seemingly perfect rental house may be spying on them. Before long, what should have been a celebratory weekend trip turns into something far more sinister", cast: ["Dave Franco", "Joe Swanberg"]), Movie(title: "Blacklight", image: UIImage(named: "Blacklight")!, releasedYear: "2022", movieRating: "4.7", boxOffice: "$43 million", moviePlot: "Travis Block, a shadowy government agent who specializes in removing operatives whose covers have been exposed, uncovers a deadly conspiracy within his own ranks that reaches the highest echelons of power.", cast: ["Mark Williams", "Mark Isham"]), Movie(title: "Nobody", image: UIImage(named: "Nobody")!, releasedYear: "2021", movieRating: "7.4", boxOffice: "57.5 million", moviePlot: "Hutch Mansell fails to defend himself or his family when two thieves break into his suburban home one night. The aftermath of the incident soon strikes a match to his long-simmering rage. In a barrage of fists, gunfire and squealing tires, Hutch must now save his wife and son from a dangerous", cast: ["Ilya Naishuller", "David Buckley"])])

let type2: Genre = Genre(type: "Periodic", movies: [Movie(title: "Baahubali", image: UIImage(named: "Baahubali")!, releasedYear: "2015", movieRating: "8", boxOffice: "650 crores", moviePlot: "In the kingdom of Mahishmati, while pursuing his love, Shivudu learns about the conflict ridden past of his family and his legacy. He must now prepare himself to face his newfound arch-enemy", cast: ["Prabhas", "Tamannaah"]), Movie(title: "GautamiputraSatakarni", image: UIImage(named: "GautamiputraSatakarni")!, releasedYear: "2017", movieRating: "6.4", boxOffice: "78 croe", moviePlot: "A chronicle of the life of Gautamiputra Satakarni (Nandamuri Balakrishna), a South Indian ruler of the Satavahana Empire in the 2nd century CE", cast: ["Nandamuri Balakrishna", "Shriya Saran"]), Movie(title: "Rudramadevi", image: UIImage(named: "Rudramadevi")!, releasedYear: "2015", movieRating: "5.2", boxOffice: "86.92 crore", moviePlot: "Rudramadevi is a 2015 Indian Telugu-language 3D biographical action film based on the life of Rudrama Devi, one of the prominent rulers of the Kakatiya dynasty in the Deccan, and one of the few ruling queens in Indian histor", cast: ["Anushka Shetty", "Allu Arjun"]), Movie(title: "Kanche", image: UIImage(named: "Kanche")!, releasedYear: "2015", movieRating: "7.9", boxOffice: "24 Cr", moviePlot: "Kanche is a 2015 Indian Telugu-language romantic war film written and directed by Krish. It stars Varun Tej, Pragya Jaiswal, and Nikitin Dheer. Produced by First Frame Entertainment, Kanche revolves around the enmity between two friends—Dhupati Haribabu and Eeshwar Prasad.", cast: ["Varun Tej", "Pragya Jaiswal"]), Movie(title: "Syeraa", image: UIImage(named: "Syeraa")!, releasedYear: "2019", movieRating: "7.3", boxOffice: "240.6 crore", moviePlot: "Ten years before the Sepoy Mutiny, Emperor Uyyalawada Narasimha Reddy of the Rayalaseema region fights the British East India Company in order to put an end to their atrocities", cast: ["Vijay Sethupathi", "Jagapathi Babu"])])

let type3: Genre = Genre(type: "Cartoon", movies: [Movie(title: "Encanto", image: UIImage(named: "Encanto")!, releasedYear: "2021", movieRating: "7.2", boxOffice: "$228 million", moviePlot: "The Madrigals are an extraordinary family who live hidden in the mountains of Colombia in a charmed place called the Encanto. The magic of the Encanto has blessed every child in the family with a unique gift -- every child except Mirabel", cast: ["Stephanie Beatriz", "María Cecilia Botero"]), Movie(title: "TurningRed", image: UIImage(named: "TurningRed")!, releasedYear: "2022", movieRating: "7", boxOffice: "$16.7 million", moviePlot: "Mei Lee is a 13-year-old girl who is torn between being her mother's obedient daughter and the chaos of her youth. As if that were not enough, when she gets too excited, she turns into a big red panda", cast: ["Rosalie Chiang", "Kajol"]), Movie(title: "Sing2", image: UIImage(named: "Sing2")!, releasedYear: "2021", movieRating: "7.4", boxOffice: "403 Million", moviePlot: "Can-do koala Buster Moon and his all-star cast of animal performers prepare to launch a dazzling stage extravaganza in the glittering entertainment capital of the world. There's just one hitch -- he has to find and persuade the world's most reclusive rock star to join them. What begins as Buster's", cast: ["Matthew McConaughey", "Reese Witherspoon"]), Movie(title: "HotelTransylvania", image: UIImage(named: "HotelTransylvania")!, releasedYear: "2005", movieRating: "4.9", boxOffice: "24 Cr", moviePlot: "A woman loves both her sons equally but her biological son hates his adopted brother. One day, they along with the other villagers are forced to evacuate and the adopted son is separated from them. He grows up with an aim to find them.", cast: ["Prabhar", "Shriya Saran"]), Movie(title: "RonsGoneWrong", image: UIImage(named: "RonsGoneWrong")!, releasedYear: "2021", movieRating: "7", boxOffice: "60 million", moviePlot: "Plot Barney is a socially awkward schoolboy who receives a robot named Ron -- a walking, talking, digitally connected device that's supposed to be his best friend. Barney is excited to finally have his own robot -- until his new toy starts to hilariously malfunction, drawing the attention of a shady", cast: ["Zach Galifianakis","Jack Dylan Grazer"])])


let categoryArray = [type1, type2, type3]
